export const UPDATE_ITINERARY = "UPDATE_ITINERARY";
export const UPDATE_DAY = "UPDATE_DAY";
export const UPDATE_CURRENT_DAY = "UPDATE_CURRENT_DAY"
export const UPDATE_ACTIVITIES = "UPDATE_ACTIVITIES";
export const UPDATE_CURRENT_ACTIVITY = "UPDATE_CURRENT_ACTIVITY";
export const REMOVE_ACTIVITY = "REMOVE_ACTIVITY";
export const REMOVE_DAY = "REMOVE_DAY";
